let levelUp = 10;
let powerLevel = 9001;
let multiplyMe = 32;
let quarterMe = 1152;
levelUp += 5;
console.log(levelUp);
powerLevel -=100;
console.log(powerLevel);
multiplyMe *=11;
console.log(multiplyMe);
quarterMe /=4;
console.log(quarterMe);
